general:
  plantuml_folder: /Users/jdbd/bin/
rest_interfaces:
  input_file: input/RestInterfaces.csv
  output_file: output/rest_interfaces_wiki.txt
  header_lines: 2
  generate_wiki: true
entities:
  input_file: input/Entities.csv
  output_file: output/entities.txt
  output_file_wiki: output/entities_wiki.txt
  image_file: entities.png
  header_lines: 2
  generate_uml: true
  generate_wiki: true
interfaces:
  input_file: input/Interfaces.csv
  output_file: output/interfaces.txt
  output_file_wiki: output/interfaces_wiki.txt
  image_file: interfaces.png
  header_lines: 4
  generate_uml: true